name: Auto Preprocessing Titanic

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  preprocess:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run preprocessing
        run: |
          python preprocessing/automate_Chris-Stefanus.py

      - name: Commit processed dataset
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add preprocessing/titanic_preprocessed.csv

          git commit -m "Auto update preprocessing" || echo "No changes"

          git push
